### ISSUE TITLE
Support for delayed starts?

### ISSUE THREAD

**Issue by dtaylor** [diegok/resque-perl#12]
I'd love to be able to schedule jobs, preferably by specifying a minimum start time (epoch or ISO would work for me). Having looked in Resque::Worker::work() it looks like it could be possible to support this by first checking to see if the next job in line has a min. start time. If if does and it's not yet that time, it could put the job onto the back of the queue or simply moving along to the next job.

If this is something you're interested in supporting, I'd be happy to contribute code.

**Comment by diegok** [comment]
Well, I will close this issue as this is very easy to implement as a plugin or as a mechanism (role) around job classes.
