### ISSUE TITLE
Using resque-perl with AnyEvent

### ISSUE THREAD

**Issue by harleypig** [diegok/resque-perl#16]
I've got a server that is accepting json data using AnyEvent. I'm trying to use resque with this event handler, so as to keep everything in one script.

I know I can create the worker with the cant_fork attribute, but what other things, if any, do I need to worry about.

If I can get this to work, I'll be glad to include documentation on how to make it work.

**Comment by diegok** [comment]
Hm... I've been thinking on change things around to make it possible to use async redis clients on resque (as I'm a heavy user of mojolicious) but I think we're going to need some big refactor as if I understand correctly all api methods should be able to accept a callback or return a future/promise.

I'm really open to this collaboration but it should include tests and proper docs. Anyway, I'm glad you care about this and I would like to chat with you about this.

**Comment by diegok** [comment]
@harleypig you can find me on irc.perl.org with the same nick as here in github.

**Comment by diegok** [comment]
I will close this as there is no more feedback. In any case, this should be done in a new module.
