### ISSUE TITLE
Feature request: Add support for Redis::Fast

### ISSUE THREAD

**Issue by djstevenson** [diegok/resque-perl#17]
We use the XS implementation of the perl client to Redis, i.e. Redis::Fast.

It's very compatible with the pure Perl Redis module, so the only code change would be to allow it in the type coercion for the 'redis' attribute. So, I would create my queue object with something like:

    my $redis = Redis::Fast->new(sentinel => ....);
    my $resque = Resque->new(redis => $redis);

I'd be happy to try this and send a pull request, if this suits you?  My opinion is that you wouldn't need to add a dependency on Redis::Fast, as its use would be entirely optional, and you can continue to use Redis as the default. What do you think?

Thank you for this module, I've only been playing with it a few days, but I do like it :)

Kindest regards,
David Stevenson

**Comment by djstevenson** [comment]
I think the coercion could be simple - if it's a blessed object, assume it's a valid Redis client class. That would allow me to use the MyEmployer::Redis class, which wraps Redis::XS in a class that, for example, looks in our config database to find where the Redis Sentinels are.

I look forward to your thoughts.

David

**Comment by diegok** [comment]
Hi David,

i'm REALLY sorry I've miss your issue for so long time :-1: . It was a problem with my email filters on that time :-(

What you've said makes a lot of sense so I'll just check your PR and if all goes well I'll be releasing this to CPAN as soon as possible. I'm very ashamed to have lost this for so looong :-(

**Comment by djstevenson** [comment]
Hey, no worries.  Thanks for your response :)

**Comment by diegok** [comment]
By any chance are you at the YAPC::EU ?

**Comment by djstevenson** [comment]
I'm afraid not, I'm house-moving in England!

**Comment by diegok** [comment]
As you've suggested, Redis::Fast is a better first option, so I've changed Resque to use it as a fist option when available and updated tests to be able to run everything choosing to skip Redis::Fast when you have both using ```REDIS_PP=1```.

On the other hand, I've moved you option to use any objet to the Redis::Sugar coercion so this is still possible if you need to use any other client.

Thank you for this suggestion! :-)

**Comment by diegok** [comment]
Released to CPAN as 0.20 !

**Comment by djstevenson** [comment]
Great, thank you very much :)
