### ISSUE TITLE
Rescue::Failures::mass_remove requeue'ing with regex queue id instead of queue argument

### ISSUE THREAD

**Issue by jc5826** [diegok/resque-perl#19]
I wanted to check to see if I have found a bug in the code under the Rescue::Failures::mass_remove(require => 1) method. 

The second argument in the following:

   $self->_requeue($item, $opt{queue})

… contains a regular expression instead of the the original $opt{queue} string passed into the method. For example: qr/(?^:meetmax_api_queue)/  instead of ‘meetmax_api_queue'. 

So it seems it’s requeue’ing the job with a different queue id than the original.

**Comment by diegok** [comment]
Yes, this is a bug and I got the same report by email. I'm glad many people find this new method useful, so I'll try to get this fixed asap.

I'm sorry for being so late on this 👎
