### ISSUE TITLE
Add support for blocking pop

### ISSUE THREAD

**Issue by thcrock** [diegok/resque-perl#2]
The upstream Ruby client has recently implemented blocking pop so the workers don't have to poll. This would be really helpful here, as well!

**Comment by djstevenson** [comment]
Hi Diego,

Nothing to add other than "yes please" to blocking reads from queues with BLPOP!  I use it for a number of queueing systems and my experience is that it works very well.

Any number of processes that are ready to do work can all BLPOP on the same list, and Redis will choose an arbitrary one to receive the item when someone else does a push onto the list.  I don't think this really lets you load-balance across worker machines, but I don't think Resque tries that anyway.

Kind regards,

David

**Comment by diegok** [comment]
@thcrock & @djstevenson sorry for being sooo late on this. I was waiting for it to happen on the ruby client but it was abandoned with the 2.x branch all toguether:

- https://github.com/resque/resque/issues/80

Today's resque does not use blpop other than for testing:

- https://github.com/resque/resque/search?q=blpop

I still thinks this can be a good fit but it also can clash with other features on resque-perl like the ability to run hooks in between tasks that we use at work. I'm planning to play around it and maybe make it optional and/or allowing to set the blpop timeout in some way.

**Comment by diegok** [comment]
It's released to CPAN as version 0.39 :tada:
