### ISSUE TITLE
Circular References

### ISSUE THREAD

**Issue by jc5826** [diegok/resque-perl#20]
There appears to be some issues with circular references:

`use Resque;
use Devel::Cycle qw(find_cycle);
my $resque = Resque->new();
$resque->worker;
$resque->failures;
find_cycle($resque);

** output **

Cycle (1):
	      $Resque::A->{'failures'} => \%Resque::Failures::B
	$Resque::Failures::B->{'resque'} => \%Resque::A

Cycle (2):
	        $Resque::A->{'worker'} => \%Resque::Worker::C
	$Resque::Worker::C->{'resque'} => \%Resque::A
`

**Comment by diegok** [comment]
Oh, I see. Thank you. I'll try to get this fixed on the next release. I'm pretty short in time, but I need to fix the issue #19 asap.
