### ISSUE TITLE
resque-worker: --redis=servername:6379 results in validation error

### ISSUE THREAD

**Issue by joshrabinowitz** [diegok/resque-perl#24]
As described at   

When the --redis=server:port option is used on resque-worker like so:

    % resque-worker --redis servername:6379 --queue A

I get this error: 

    Attribute (redis) does not pass the type constraint because: Validation failed for 
    'Sugar::Redis' with value [ "servername:6379" ] at constructor Resque::new 
    (defined at ...site_perl/5.24.0/Resque.pm line 165) line 58

[PR #23 provides a fix for the issue and allows resque-worker to connect to remote redis servers.]

**Comment by diegok** [comment]
Thank you @joshrabinowitz !, I've already released it to CPAN. This script comes from one I use in my company and there the config comes from other place so I've never used it. Please let me know if you need anything else from this worker runner as I'm completely open to improvements.
